language: ruby

before_install:
  - gem install bundler

gemfile:
  - Gemfile

rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=sqlite
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake spec
